// import { ThemeProvider } from "@mui/material/styles";
// import theme from "@/theme/theme";
// import Footer from "@/components/footer/Footer";
// import Header from "@/components/header/Header";
// import "./globals.css";

// // Import font using `next/font`
// import { Roboto } from "next/font/google";

// const roboto = Roboto({
//   subsets: ["latin"],
//   weight: ["400", "500", "700"], // Removed 600
//   display: "swap",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={roboto.className}>
//       <body>
//         <ThemeProvider theme={theme}>
//           <Header />
//           {children}
//           <Footer />
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }

import { ThemeProvider } from "@mui/material/styles";
import theme from "@/theme/theme";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import "./globals.css";

// Import font using `next/font`
import { Ubuntu } from "next/font/google";

// const ubuntu = Ubuntu({
//   subsets: ["latin"],
//   weight: ["400", "500", "700"], // Adjust weights as needed
//   display: "swap",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Geist:wght@100..900&display=swap"
          rel="stylesheet"
        ></link> */}
        <link
          href="https://fonts.googleapis.com/css2?family=Reddit+Sans:ital,wght@0,200..900;1,200..900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body className="ubuntu-font">
        <ThemeProvider theme={theme}>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
